/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dinnertime;

import dinnertime.controller.DinnerTimeController;
import dinnertime.controller.IdentifiedContextInterceptorConfig;
import dinnertime.db.DatabaseConfig;
import dinnertime.gdrive.GoogleDriveConfig;
import dinnertime.service.DinnerTimeService;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan(
    basePackageClasses = {
        IdentifiedContextInterceptorConfig.class,
        DinnerTimeController.class,
        DinnerTimeService.class,
        DatabaseConfig.class,
        GoogleDriveConfig.class
    }
)
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
